spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: password

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: article
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.aszjch.demoapp.domain.article
    admin:
      auto-create: true
    template:
      default-topic: "articles-created"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


minio:
  url: http://localhost:9000
  username: minio
  password: minio123
  bucket: test-bucket
